-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text NOT NULL,
    sender_id text NOT NULL,
    message text NOT NULL,
    is_admin_message boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS for messages
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Allow public access (for demo purposes, or adjust as needed)
CREATE POLICY "Allow public access to messages"
ON public.messages
FOR ALL
USING (true)
WITH CHECK (true);

-- Create registered_users view
-- This view exposes auth.users data safely to the API
CREATE OR REPLACE VIEW public.registered_users AS
SELECT
    id,
    email,
    raw_user_meta_data->>'etsy_store_url' as etsy_store_url,
    created_at,
    last_sign_in_at
FROM auth.users;

-- Grant access to the view (if needed, usually public role needs select)
GRANT SELECT ON public.registered_users TO anon, authenticated, service_role;
