-- ====================================================================================
-- ================== ETSY STORE ADMIN DASHBOARD - SUPABASE KURULUMU ==================
-- ====================================================================================
-- Bu betik, uygulama için gerekli tüm veritaban› yap›s›n›, güvenlik kurallar›n›
-- ve baﬂlang›ç verilerini oluﬂturur. Lütfen tamam›n› kopyalay›p Supabase
-- SQL Editor'de çal›ﬂt›r›n.

-- BÖLÜM 1: TABLOLARIN OLUﬁTURULMASI
-- ------------------------------------------------------------------------------------

-- Müﬂteri verilerini saklamak için `customers` tablosu
CREATE TABLE IF NOT EXISTS public.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    avatar text,
    plan text NOT NULL CHECK (plan IN ('Basic', 'Pro', 'Premium')),
    status text NOT NULL CHECK (status IN ('Active', 'Churned', 'Trial')),
    spent numeric NOT NULL,
    join_date timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.customers IS 'Abonelik sahibi müﬂterilerin bilgilerini saklar.';

-- Fiyatland›rma paketlerini saklamak için `packages` tablosu
CREATE TABLE IF NOT EXISTS public.packages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price numeric NOT NULL,
    features text[] NOT NULL,
    is_popular boolean DEFAULT false NOT NULL,
    subscribers integer
);
COMMENT ON TABLE public.packages IS 'Sat›lan abonelik paketlerini ve özelliklerini tan›mlar.';

-- ‹letiﬂim formu arac›l›€›yla toplanan potansiyel müﬂterileri saklamak için `leads` tablosu
CREATE TABLE IF NOT EXISTS public.leads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    store_url text,
    selected_package text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.leads IS 'Ana sayfadaki formdan gelen potansiyel müﬂteri kay›tlar›n› tutar.';

-- Ana sayfan›n dinamik içeri€ini saklamak için `site_content` tablosu
CREATE TABLE IF NOT EXISTS public.site_content (
    id bigint PRIMARY KEY,
    content jsonb NOT NULL
);
COMMENT ON TABLE public.site_content IS 'Ana sayfan›n tüm metin içeri€ini JSON format›nda saklar.';

-- Dönüﬂüm artt›r›c› (sosyal kan›t bildirimleri) ayarlar›n› saklamak için `conversion_settings` tablosu
CREATE TABLE IF NOT EXISTS public.conversion_settings (
    id bigint PRIMARY KEY,
    is_enabled boolean DEFAULT false NOT NULL,
    templates text[] NOT NULL,
    min_interval integer NOT NULL
);
COMMENT ON TABLE public.conversion_settings IS 'Sosyal kan›t bildirimlerinin ayarlar›n› yönetir.';

-- Site ad› ve logo gibi genel site ayarlar›n› saklamak için `site_settings` tablosu
CREATE TABLE IF NOT EXISTS public.site_settings (
    id bigint PRIMARY KEY,
    site_name text NOT NULL,
    logo_url text
);
COMMENT ON TABLE public.site_settings IS 'Genel site ayarlar›n› (isim, logo vb.) saklar.';

-- BÖLÜM 2: RPC FONKS‹YONUNUN OLUﬁTURULMASI
-- ------------------------------------------------------------------------------------
-- Yönetici panelinde tüm kay›tl› kullan›c›lar› listelemek için bir fonksiyon.
-- Bu fonksiyon, RLS'yi atlayarak `auth.users` tablosundan veri okumak için gereklidir.
CREATE OR REPLACE FUNCTION public.get_all_users()
RETURNS TABLE (
    id uuid,
    email text,
    etsy_store_url text,
    created_at timestamptz
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        u.id,
        u.email,
        u.raw_user_meta_data->>'etsy_store_url' as etsy_store_url,
        u.created_at
    FROM auth.users u;
$$;
COMMENT ON FUNCTION public.get_all_users() IS 'Yönetici panelinde tüm kullan›c›lar› listelemek için auth.users tablosunu okur.';


-- BÖLÜM 3: BAﬁLANGIÇ VER‹LER‹N‹N EKLENMES‹ (SEEDING)
-- ------------------------------------------------------------------------------------
-- Uygulaman›n ilk çal›ﬂt›rmada boﬂ görünmemesi için örnek veriler eklenir.

-- Örnek Müﬂteriler
INSERT INTO public.customers (name, email, avatar, plan, status, spent, join_date) VALUES
('Ayﬂe Y›lmaz', 'ayse.yilmaz@example.com', 'https://api.dicebear.com/8.x/initials/svg?seed=Ayse', 'Pro', 'Active', 249.99, '2023-10-15T10:00:00Z'),
('Mehmet Kaya', 'mehmet.kaya@example.com', 'https://api.dicebear.com/8.x/initials/svg?seed=Mehmet', 'Premium', 'Active', 899.50, '2023-08-22T14:30:00Z'),
('Zeynep Demir', 'zeynep.demir@example.com', 'https://api.dicebear.com/8.x/initials/svg?seed=Zeynep', 'Basic', 'Churned', 59.90, '2023-11-01T09:15:00Z'),
('Mustafa Can', 'mustafa.can@example.com', 'https://api.dicebear.com/8.x/initials/svg?seed=Mustafa', 'Pro', 'Trial', 0, NOW() - interval '3 days')
ON CONFLICT DO NOTHING;

-- Örnek Paketler
INSERT INTO public.packages (id, name, price, features, is_popular, subscribers) VALUES
(1, 'Basic', 29, '{"Temel SEO Analizi", "Haftal›k Raporlama", "50 Anahtar Kelime Takibi", "E-posta Deste€i"}', false, 128),
(2, 'Pro', 79, '{"Geliﬂmiﬂ SEO Analizi", "Günlük Raporlama", "250 Anahtar Kelime Takibi", "Rakip Analizi", "Öncelikli E-posta Deste€i"}', true, 342),
(3, 'Premium', 149, '{"Tüm Pro Özellikleri", "Limitsiz Anahtar Kelime Takibi", "API Eriﬂimi", "Özel Dan›ﬂmanl›k", "Telefon ve E-posta Deste€i"}', false, 74)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    features = EXCLUDED.features,
    is_popular = EXCLUDED.is_popular,
    subscribers = EXCLUDED.subscribers;

-- Ana Sayfa ‹çeri€i
INSERT INTO public.site_content (id, content) VALUES
(1, '{
    "hero": {
        "title": "Etsy Ma€azan›z› Zirveye Taﬂ›y›n",
        "subtitle": "Yapay zeka destekli analiz araçlar›m›zla sat›ﬂlar›n›z› art›r›n, rakiplerinizin önüne geçin ve iﬂinizi büyütün. Baﬂlamak için ma€aza URL''nizi girin.",
        "formPlaceholder": "Etsy ma€aza URL''nizi buraya yap›ﬂt›r›n...",
        "formButton": "Analize Baﬂla"
    },
    "features": {
        "title": "Baﬂar› ‹çin ‹htiyac›n›z Olan Her ﬁey",
        "subtitle": "Platformumuz, Etsy ma€azan›z›n her yönünü optimize etmeniz için güçlü ve kullan›m› kolay araçlar sunar.",
        "cards": [
            { "title": "Ak›ll› Anahtar Kelime Önerileri", "description": "Yapay zeka algoritmalar›m›z, ürünleriniz için en yüksek dönüﬂüm potansiyeline sahip anahtar kelimeleri bulur." },
            { "title": "Detayl› Rakip Analizi", "description": "Rakiplerinizin stratejilerini, fiyatland›rmalar›n› ve en çok satan ürünlerini an›nda keﬂfedin." },
            { "title": "Kapsaml› Performans Raporlar›", "description": "Ma€azan›z›n sa€l›€›n› tek bir panelden takip edin. Ziyaretçi say›lar›, sat›ﬂ oranlar› ve daha fazlas›." }
        ]
    },
    "pricing": {
        "title": "‹ﬂletmenize Uygun Plan› Seçin",
        "subtitle": "‹ster yeni baﬂl›yor olun, ister sat›ﬂlar›n›z› ölçeklendirmek isteyin, her ihtiyaca uygun bir çözümümüz var."
    },
    "proof": {
        "title": "Binlerce Mutlu Ma€aza Sahibi",
        "subtitle": "Platformumuzu kullanarak sat›ﬂlar›n› ve görünürlüklerini art›ran baﬂar›l› sat›c›lar›n aras›na kat›l›n."
    }
}')
ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content;

-- Dönüﬂüm Artt›r›c› Ayarlar›
INSERT INTO public.conversion_settings (id, is_enabled, templates, min_interval) VALUES
(1, true, '{"{{name}}, {{package}} paketini {{time}} sat›n ald›.", "{{name}} az önce {{package}} paketine abone oldu."}', 8)
ON CONFLICT (id) DO UPDATE SET
    is_enabled = EXCLUDED.is_enabled,
    templates = EXCLUDED.templates,
    min_interval = EXCLUDED.min_interval;

-- Genel Site Ayarlar›
INSERT INTO public.site_settings (id, site_name, logo_url) VALUES
(1, 'Etsy Admin Pro', null)
ON CONFLICT (id) DO UPDATE SET
    site_name = EXCLUDED.site_name,
    logo_url = EXCLUDED.logo_url;


-- BÖLÜM 4: SATIR SEV‹YES‹ GÜVENL‹K (RLS) POL‹T‹KALARI
-- ------------------------------------------------------------------------------------
-- Tablolar için RLS'yi etkinleﬂtir ve politikalar› tan›mla.

-- RLS'yi etkinleﬂtir
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversion_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Mevcut politikalar› temizle (varsa)
DROP POLICY IF EXISTS "Allow public read access" ON public.customers;
DROP POLICY IF EXISTS "Allow admin full access" ON public.customers;
DROP POLICY IF EXISTS "Allow public read access" ON public.packages;
DROP POLICY IF EXISTS "Allow admin full access" ON public.packages;
DROP POLICY IF EXISTS "Allow public insert access" ON public.leads;
DROP POLICY IF EXISTS "Allow admin full access" ON public.leads;
DROP POLICY IF EXISTS "Allow public read access" ON public.site_content;
DROP POLICY IF EXISTS "Allow admin full access" ON public.site_content;
DROP POLICY IF EXISTS "Allow public read access" ON public.conversion_settings;
DROP POLICY IF EXISTS "Allow admin full access" ON public.conversion_settings;
DROP POLICY IF EXISTS "Allow public read access" ON public.site_settings;
DROP POLICY IF EXISTS "Allow admin full access" ON public.site_settings;

-- `customers` tablosu politikalar›
CREATE POLICY "Allow public read access" ON public.customers FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.customers FOR ALL USING (auth.role() = 'authenticated');

-- `packages` tablosu politikalar›
CREATE POLICY "Allow public read access" ON public.packages FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.packages FOR ALL USING (auth.role() = 'authenticated');

-- `leads` tablosu politikalar›
CREATE POLICY "Allow public insert access" ON public.leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin full access" ON public.leads FOR ALL USING (auth.role() = 'authenticated');

-- `site_content` tablosu politikalar›
CREATE POLICY "Allow public read access" ON public.site_content FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.site_content FOR ALL USING (auth.role() = 'authenticated');

-- `conversion_settings` tablosu politikalar›
CREATE POLICY "Allow public read access" ON public.conversion_settings FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.conversion_settings FOR ALL USING (auth.role() = 'authenticated');

-- `site_settings` tablosu politikalar›
CREATE POLICY "Allow public read access" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Allow admin full access" ON public.site_settings FOR ALL USING (auth.role() = 'authenticated');


-- BÖLÜM 5: DEPOLAMA (STORAGE) AYARLARI
-- ------------------------------------------------------------------------------------
-- UYARI: Depolama alanlar› (bucket) SQL ile oluﬂturulamaz.
-- Lütfen Supabase arayüzünden 'Storage' bölümüne gidin ve aﬂa€›daki iki bucket'›
-- 'Public' olarak iﬂaretleyerek oluﬂturun:
-- 1. proof_images
-- 2. site_assets
--
-- Bu iﬂlemi yapt›ktan sonra, aﬂa€›daki SQL politikalar› bu alanlara eriﬂimi yönetecektir.

-- Önceki çak›ﬂan depolama politikalar›n› temizle
DROP POLICY IF EXISTS "Allow public read access for proof_images" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated CRUD for proof_images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public read access for site_assets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated CRUD for site_assets" ON storage.objects;

-- `proof_images` bucket'› için politikalar
CREATE POLICY "Allow public read access for proof_images"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'proof_images');

CREATE POLICY "Allow authenticated CRUD for proof_images"
ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'proof_images')
WITH CHECK (bucket_id = 'proof_images');

-- `site_assets` bucket'› için politikalar
CREATE POLICY "Allow public read access for site_assets"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'site_assets');

CREATE POLICY "Allow authenticated CRUD for site_assets"
ON storage.objects FOR ALL
TO authenticated
USING (bucket_id = 'site_assets')
WITH CHECK (bucket_id = 'site_assets');

-- ====================================================================================
-- ============================ KURULUM TAMAMLANDI ==================================
-- ====================================================================================